package com.shortener.url.domain;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * Url is the core Aggregate Root — owns all lifecycle business rules.
 *
 * Design decisions:
 * - id = Snowflake (monotonic, B-tree friendly, globally unique across shards)
 * - shortCode indexed uniquely — the hot-path lookup key
 * - Soft-delete only (is_active flag) — data retained for analytics
 * - Business logic encapsulated here, not in services (rich domain model)
 */
@Entity
@Table(
    name = "urls",
    indexes = {
        @Index(name = "idx_urls_short_code",   columnList = "short_code",   unique = true),
        @Index(name = "idx_urls_user_id",      columnList = "user_id"),
        @Index(name = "idx_urls_created_at",   columnList = "created_at"),
        @Index(name = "idx_urls_expires_at",   columnList = "expires_at"),
        @Index(name = "idx_urls_custom_alias", columnList = "custom_alias", unique = true)
    }
)
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Url {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;  // Snowflake ID — NOT auto-generated by DB

    @Column(name = "short_code", length = 10, nullable = false, unique = true, updatable = false)
    private String shortCode;

    @Column(name = "original_url", length = 2048, nullable = false)
    private String originalUrl;

    @Column(name = "user_id")
    private Long userId;  // null = anonymous URL

    @Column(name = "title", length = 255)
    private String title;

    @Column(name = "custom_alias", length = 50, unique = true)
    private String customAlias;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "max_clicks")
    private Long maxClicks;

    @Column(name = "total_clicks", nullable = false)
    @Builder.Default
    private long totalClicks = 0L;

    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private boolean active = true;

    @Column(name = "is_private", nullable = false)
    @Builder.Default
    private boolean privateUrl = false;

    @Column(name = "password_hash")
    private String passwordHash;

    @Column(name = "utm_source",   length = 100)
    private String utmSource;

    @Column(name = "utm_medium",   length = 100)
    private String utmMedium;

    @Column(name = "utm_campaign", length = 100)
    private String utmCampaign;

    @Column(name = "utm_term",     length = 100)
    private String utmTerm;

    @Column(name = "utm_content",  length = 100)
    private String utmContent;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private Instant updatedAt;

    // ─── Business Rules ───────────────────────────────────────────────────

    /**
     * True if this URL can serve a redirect right now.
     * Checked on the hot redirect path — fast (no I/O).
     */
    public boolean isRedirectAllowed() {
        return active && !isExpired() && !isClickLimitReached();
    }

    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }

    public boolean isClickLimitReached() {
        return maxClicks != null && totalClicks >= maxClicks;
    }

    public boolean requiresPassword() {
        return passwordHash != null && !passwordHash.isBlank();
    }

    /** Increment click counter; auto-deactivate when maxClicks is reached. */
    public void recordClick() {
        this.totalClicks++;
        if (isClickLimitReached()) {
            this.active = false;
        }
    }

    /** Soft-delete: keep the record, analytics intact. */
    public void deactivate() {
        this.active = false;
    }
}
